apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: github-actions-role
rules:
- apiGroups: [""]
  resources: ["pods", "deployments"]
  verbs: ["create", "update", "list", "get"]
