name: CI/CD Pipeline
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean package

      - name: Write Dockerfile
        run: |
          echo "FROM tomcat:9.0-jre11" > Dockerfile
          echo "COPY target/*.war /usr/local/tomcat/webapps/" >> Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:${{ github.sha }} \
            -t ${{ secrets.DOCKER_HUB_USERNAME }}/my-app:latest \
            --push .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Debug AWS configuration
        run: |
          aws sts get-caller-identity
          aws eks list-clusters --region us-east-1

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: v1.21.0

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name demo-cluster --region us-east-1 --kubeconfig ./kubeconfig
          export KUBECONFIG=./kubeconfig

      - name: Debug kubeconfig
        run: |
          cat ./kubeconfig

      - name: Debug IAM permissions
        run: |
          aws sts get-caller-identity
          aws eks describe-cluster --name demo-cluster --region us-east-1

      - name: Debug Kubernetes permissions
        run: |
          kubectl --kubeconfig ./kubeconfig auth can-i create deployments
          kubectl --kubeconfig ./kubeconfig auth can-i create services
          kubectl --kubeconfig ./kubeconfig auth can-i create roles
          kubectl --kubeconfig ./kubeconfig auth can-i create rolebindings

      - name: Update Deployment file
        run: |
          sed -i 's|$DOCKER_HUB_USERNAME|${{ secrets.DOCKER_HUB_USERNAME }}|g' k8s/Deployment.yaml
          sed -i 's|:latest|:${{ github.sha }}|g' k8s/Deployment.yaml

      - name: Create Kubernetes resources
        run: |
          kubectl --kubeconfig ./kubeconfig apply -f k8s/ServiceAccount.yaml
          kubectl --kubeconfig ./kubeconfig get events --sort-by=.metadata.creationTimestamp
          
          kubectl --kubeconfig ./kubeconfig apply -f k8s/Role.yaml
          kubectl --kubeconfig ./kubeconfig get events --sort-by=.metadata.creationTimestamp
          
          kubectl --kubeconfig ./kubeconfig apply -f k8s/RoleBinding.yaml
          kubectl --kubeconfig ./kubeconfig get events --sort-by=.metadata.creationTimestamp
          
          kubectl --kubeconfig ./kubeconfig apply -f k8s/Deployment.yaml
          kubectl --kubeconfig ./kubeconfig get events --sort-by=.metadata.creationTimestamp
          
          kubectl --kubeconfig ./kubeconfig apply -f k8s/Service.yaml
          kubectl --kubeconfig ./kubeconfig get events --sort-by=.metadata.creationTimestamp

      - name: Check for errors
        run: |
          kubectl --kubeconfig ./kubeconfig get all
          kubectl --kubeconfig ./kubeconfig get events --sort-by=.metadata.creationTimestamp
